### PR TITLE
feat: implemented log format suggestions for issue #122

### LINKED ISSUE #122: [Feature Request]: Performance logging format
### Related problem

Hey there! 👋 I wanted to start out by saying thank you so much for all of your incredible work on this mod. I have only positive things to say about everything you've created here! Your work is appreciated and it's brought my friends and I many fun nights. 😄

#### The Related Issue

When monitoring the performance of the Antistasi server using Grafana, the key value pairs in the log message don't follow a standard logging format. This makes it a little more challenging to automatically parse these fields for metrics gathering.

#### The Related Code

https://github.com/igorkis-scrts/A3-Antistasi-Plus/blob/1a5964cf55f67f7cfc9d9e0ba1ec0112314b070d/A3A/addons/core/functions/Base/fn_logPerformance.sqf#L33

🔗 [Here is the original logfmt definition](https://brandur.org/logfmt)
🔗 [Here is the logfmt definition from grafana](https://grafana.com/docs/loki/latest/logql/log_queries/#logfmt)

1. Any metric fields go into key value pairs separated by an `Warlevel=3`
2. Any floating point values in metrics are placed into quotations e.g. `ServerFPS="30.2131"`

Here is the how the fields appear in a monitoring solution when parsed as logfmt with the current logging setup in Antistasi Plus. Notice how it does find the field but due to the key/value pair template format in `fn_logPerformance.sqf`, grafana groups the key with the value.
image

### Proposed feature

My proposed feature is to change the performance logging pattern from the current to the proposed:

Current: `ServerFPS:%1, Players:%11, DeadUnits:%2, AllUnits:%3, UnitsAwareOfEnemies:%14...`
Proposed: `ServerFPS=%1 Players=%11 DeadUnits=%2 AllUnits=%3 UnitsAwareOfEnemies=%14...`

### Alternative solutions

1. Make number of spaces between the key and value always == `1` e.g. `key: value` instead of `key:value` or `key:  value`
2. Use JSON logging format e.g. 
```json
{ "ServerFPS":"16.5289", "Entities":"926" }
```

#### Example current message:

```shell
8:09:08 2023-03-01 08:09:08:359 | Antistasi | Info | File: A3A_fnc_logPerformance |  ServerFPS:16.5289, Players:4, DeadUnits:58, AllUnits:106, UnitsAwareOfEnemies:48, AllVehicles:99, WreckedVehicles:3, Entities:926, GroupsRebels:7, GroupsInvaders:0, GroupsOccupants:29, GroupsCiv:3, GroupsTotal:39, GroupsCombatBehaviour:10, Faction Cash:3959, HR:71, OccAggro: 29, InvAggro: 0, Warlevel: 3, RivalsActivityLevel: 5
```

#### Example Proposed Log message:

```shell
8:09:08 2023-03-01 08:09:08:359 | Antistasi | Info | File=A3A_fnc_logPerformance | ServerFPS="16.5289" Players=4 DeadUnits=58 AllUnits=106 UnitsAwareOfEnemies=48 AllVehicles=99 WreckedVehicles=3 Entities=926 GroupsRebels=7 GroupsInvaders=0 GroupsOccupants=29 GroupsCiv=3 GroupsTotal=39 GroupsCombatBehaviour=10 FactionCash=3959 HR=71 OccAggro=29 InvAggro=0 Warlevel=3 RivalsActivityLevel=5
```

#### Monitoring Antistasi in Grafana:
image

### PR DESCRIPTION
**Pull request by brittonhayes**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information: I have changed the performance logging format to follow the suggestions outlined in issue #122 (related to monitoring Antistasi logs using services like Grafana).

### Please specify which Issue this PR Resolves.
closes #122

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Run the Antistasi server and monitor for logs with `File=A3A_fnc_logPerformance`
********************************************************
Notes:

### CODE REVIEW

**Comment by igorkis-scrts** [comment]
Hi! First of, thanks for contribution!
Seems to be pretty good addition, if that makes log parsing easier this should be done, of course. 
I'll test and if everything is fine this PR will be merged

**Comment by brittonhayes** [comment]
Happy to contribute! I appreciate you being so responsive. Let me know if ya need me to change anything after your testing.

**Comment by igorkis-scrts** [comment]
I've tested it, it's fine. 
Please, could you change PR destination to unstable - it's an actual dev branch.

**Review by igorkis-scrts — APPROVED** [review]

**Comment by igorkis-scrts** [comment]
Merged it into exception, becuase it has no conflicts with the upcoming patch.

**Comment by brittonhayes** [comment]
Awesome! Thank you!

**Pull request merged**
