### PR TITLE
Update Stringtable.xml 

### PR DESCRIPTION
**Pull request by vbnshi**
What type of PR is this.
 Bug
[√] Change
 Enhancement
What have you changed and why?
Information:
I translated most of the content of SCRT Stringtable.xml in Chinesesimp, maybe not so accurate, but I sure Chinese people can understand most of my translation

Please specify which Issue this PR Resolves.
closes #XXXX

Please verify the following and ensure all checks are completed.
 Have you loaded the mission in LAN host?
 Have you loaded the mission on a dedicated server?
Is further testing or are further changes required?
 No
[√] Yes (Please provide further detail below.)
How can the changes be tested?
Steps: This is entirely untested.Because I don't know how to pack pbo.

### CODE REVIEW

**Comment by vbnshi** [comment]
I don't know how to change it, so I re-PR

**Comment by vbnshi** [comment]
sry guy,this is my first time using github, is this changed?

**Comment by igorkis-scrts** [comment]
Yeah, it targets unstable.

**Comment by igorkis-scrts** [comment]
I uploaded 2.1 to `unstable`, resolve merge conflicts and it will be included into the next update.

**Comment by igorkis-scrts** [comment]
Seeems that PR has changes from previous version so it will break the build. I think it's better to create a new pull request with just `Stringtable.xml` (just copy-paste them into new PR). so it will be easily merged with the current state of codebase.

**Comment by vbnshi** [comment]
I found that the Stringtable.xml of unstable is different from the Stringtable.xml of master, which version should I use to translate?

**Comment by vbnshi** [comment]
The unstable Stringtable.xml deleted some text, so should I delete the same text in the master version?

**Comment by vbnshi** [comment]
@igorkis-scrts

**Comment by igorkis-scrts** [comment]
> I found that the Stringtable.xml of unstable is different from the Stringtable.xml of master, which version should I use to translate?
Unstable one. After unstable will be fully ready, it will be merget into master.

> The unstable Stringtable.xml deleted some text, so should I delete the same text in the master version?
Yes.

**Pull request closed without merging**
