### PR TITLE
Add: Simplified Chinese translation

### PR DESCRIPTION
**Pull request by GoldJohnKing**
## What type of PR is this.
3. [x] Enhancement

### What have you changed and why?
Information:
Add: Simplified Chinese translation

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No

********************************************************
Notes:

This translation was first contributed to [official-antistasi-community/A3-Antistasi](https://github.com/official-antistasi-community/A3-Antistasi) by me(@GoldJohnKing) and a player in my clan named @xiduola early this year. (See https://github.com/official-antistasi-community/A3-Antistasi/pull/1939)

Once we found this folk, we migrated the translation to this repo and finished the remaining translate.

However there are still many contents not in stringtable.xml so we cannot translate, hope it will finally solved one day.

### CODE REVIEW

**Comment by igorkis-scrts** [comment]
Thank you for PR, your translation will be merged with the upcoming 1.7 update.
About non-stringtable.xml strings - well, situation slowly gets better, but there is a long way to go before every string in the scenario will be translateable.

**Comment by igorkis-scrts** [comment]
This PR needs to be updated to be merged, as many strings to Stringtable.xml had been added.

**Comment by GoldJohnKing** [comment]
Which branch should I use? I forked from unstable and it's still behind.

**Comment by GoldJohnKing** [comment]
Haven't done yet.

**Comment by GoldJohnKing** [comment]
Done! Please check!

**Comment by igorkis-scrts** [comment]
Thank you for contribution, i will check.
If everything is fine, it will be released with 1.7.5 update which will happen today.

**Pull request merged**
